### ISSUE TITLE
Could not display pull requests

### ISSUE THREAD

**Issue by panchalkalpesh** [jkup/pullit#14]
> Version: 1.3.0

Currently getting the following error:

```
$ pullit
Error: could not display pull requests. Please make sure this is a valid repository.
```

**Comment by jkup** [comment]
Hi @panchalkalpesh! Can you paste me the results of

```
git config --get remote.origin.url
```

from that same directory? Thanks!

**Comment by jkup** [comment]
@panchalkalpesh Thanks! Right now this app only works for projects that are hosted on github.com. Is your project on github? If so, it might just be a problem where I assume the origin branch will always be the github one, maybe yours is different?

**Comment by jkup** [comment]
Closing for now, let me know if this project is on github and I'll re-open!
